# Site settings
title: Kenneth Buck
email: kenneth at kennethbuck dot com
description: These are my thoughts, not yours.
baseurl: ""
url: "http://kennethbuck.ca"

author:
  name      : 'Kenneth Buck'
  email     : kenneth@kennethbuck.ca
  url       : http://kennethbuck.ca
  twitter   : https://twitter.com/kdbuck
  github    : https://github.com/kennethdavidbuck
  googleplus: https://plus.google.com/u/0/111219532177253049109/posts/p/pub
  linkedin  : https://www.linkedin.com/in/kdbuck

github: https://github.com/kennethdavidbuck
disqus_shortname: "kennethbuck"
#google_analytics: UA-75008396-1

paginate: 5
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
